services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - bookify-db
    ports:
      - "8083:8080"
      - "8084:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  bookify-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Bookify.Db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=as_1380MahaN_sd  # Change this to a secure password
      - MSSQL_DATABASE=Bookify  
      - ConnectionStrings__DataBase=Data Source=bookify-db;Initial Catalog=Bookify;User Id=sa;Password=as_1380MahaN_sd;TrustServerCertificate=True;
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
